# Generated by Django 5.2.4 on 2025-07-21 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brightway", "0002_student_date_of_birth_alter_feereport_month_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("date_of_joining", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="attendancereport",
            name="month",
        ),
        migrations.RemoveField(
            model_name="attendancereport",
            name="session",
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendancereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("leave", "Leave"),
                ],
                max_length=7,
            ),
        ),
    ]
